language: java
jdk:
- oraclejdk8
sudo: false
notifications:
  email:
  - bilalwahla@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
before_script:
  - chmod +x gradlew
script:
- ./gradlew check
- ./gradlew jacocoTestReport
after_success:
- bash <(curl -s https://codecov.io/bash)
